#!/bin/bash
# Not a full path, so be careful about changing directories
DIR=$( dirname "${BASH_SOURCE[0]}" )
# Warning: changing this to 'php' will cause an infinite redirection loop
# in ShipIt executables.
/usr/local/hphpi/bin/hhvm -c "${DIR}/fb_shipit.ini" "$@"
